version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run docs:build
      - run: |
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker build -t mtijnnl/workshop:latest .
        docker push mtijnnl/workshop:latest