version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: angular-build
          command: npm run build --no-progress
      - run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker build -t mtijnnl/workshop:latest .
          docker push mtijnnl/workshop:latest

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          context: docker