version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:latest
  machine: true

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps

      - run:
          name: 'Install dependencies'
          command: npm install

      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: 'Build project'
          command: npm run docs:build

  docker-build:
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: 'Build project'
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker build -t mtijnnl/workshop:latest .
            docker push mtijnnl/workshop:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - install-dependencies
      - build: { requires: [install-dependencies] }
      - docker-build: { requires: [build] }